[package]
name = "beanstalk-rs"
version = "0.0.4"
authors = [ "jbcrail@gmail.com" ]

[lib]
name = "beanstalk"
path = "src/lib.rs"
crate_type = ["rlib", "dylib"]

[[bin]]
name = "beanstalk-cli"
path = "src/bin/main.rs"

[dependencies]
getopts = "0.2.14"
linenoise-rust = "0.2.0"
bufstream = "0.1.2"
